spring:
  profiles: dev
server:
  port: 10002
eureka:
  instance:
    hostname: demo2
    appname: demo2-service
    virtual-host-name: demo2-service
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka/
    
