spring:
  profiles: dev
server:
  port: 10001
eureka:
  instance:
    hostname: demo1
    appname: github-demo1-service
    virtual-host-name: loving.demo1.service
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka/
ribbon:
  eureka:
   enabled: true
  NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
  ServerListRefreshInterval: 30000
  DeploymentContextBasedVipAddresses: demo1service
