spring:
  profiles: dev
server:
  port: 10001
eureka:
  instance:
    hostname: demo1
    appname: demo1-service
    virtual-host-name: demo1-service
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka/
