spring:
  profiles: dev
server:
  port: 10001
eureka:
  instance:
    hostname: demo1
    appname: github-demo1-service
    virtual-host-name: loving.demo1.service
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
