spring:
  profiles: dev
cassandra:
  contactpoints: 10.9.42.203
  port: 9042
  keyspace: pois_dev

---

spring:
  profiles: qa
cassandra:
  contactpoints: 172.28.24.32
  port: 9042
  keyspace: pois_qa