spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.9.42.203:8087/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.order.service

server:
  port: 29268

cassandra:
  contactpoints: 10.9.42.203
  port: 9042
  keyspace: pois_dev

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit-dev
  host: 10.9.42.203
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

zookeeper:
  connect: 10.9.42.203:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200

group:
  id: changhongit-book-es-group-dev
  
metadata:
  broker:
    list: 10.9.42.203:9092
request:
  required:
    acks: 0

topic: order-service
num:
  partitions: 8
log:
  retention:
    hours: 1

auto:
  commit:
    nterval:
      ms: 1000
  offset:
    reset: smallest

kafka:
  topic: ORDER-INFO

checkToken:
  endpoint: http://10.9.42.203:8087/security/oauth/check_token?token=%s

userRegister:
  endpoint: http://10.9.42.203:8087/security/guanhutong3g/register

oauth2:
  updatepassword: http://10.9.42.203:8087/security/users/password.update
  userDetails: http://10.9.42.203:8087/security/users/{uuid}
  userMyInfo: http://10.9.42.203:8087/security/users/myInfo
loginOauth2:
  endpoint: http://10.9.42.203:8087/security/oauth/accesstoken
  
productprice:
  detail:
    uri: http://10.9.42.203:8087/productprices/
    
employeeServer:
  address: http://10.9.42.203:8087/employees/    
companyServer:
  address: http://10.9.42.203:8087/companies/
order:
  schema:
    config: http://10.9.42.203:8087/config/orderMessageSchema-dev.json
---

spring:
  profiles: qa

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.28.24.32:8761/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.order.service

server:
  port: 19303

cassandra:
  contactpoints: 172.28.24.32
  port: 9042
  keyspace: pois_qa


elasticsearch:
  clusterName: changhongit-qa
  host: 172.28.24.32
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
zookeeper:
  connect: 172.28.24.32:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200

group:
  id: changhongit-book-es-group-qa

metadata:
  broker:
    list: 172.28.24.32:9092
request:
  required:
    acks: 0

topic: order-service
num:
  partitions: 8
log:
  retention:
    hours: 1


auto:
  commit:
    nterval:
      ms: 1000
  offset:
    reset: smallest

kafka:
  topic: ORDER-INFO

checkToken:
  endpoint: http://172.28.24.32:19301/security/oauth/check_token?token=%s

userRegister:
  endpoint: http://172.28.24.32:19301/security/guanhutong3g/register
  
loginOauth2:
  endpoint: http://172.28.24.32:19301/security/oauth/accesstoken
  
endpoints:
  health:
    id: health
    sensitive: false
    enabled: true
    
---

spring:
  profiles: product
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://103.245.128.220:8087/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.order.service

server:
  port: 39005

cassandra:
  contactpoints: 120.24.169.69
  port: 9042
  keyspace: pois_qa

checkToken:
  endpoint: http://120.24.169.69:8087/security/oauth/check_token?token=%s
  
userRegister:
  endpoint: http://172.28.4.220:8087/security/guanhutong3g/register  

loginOauth2:
  endpoint: http://120.24.169.69:8087/security/oauth/accesstoken
  
endpoints:
  health:
    id: health
    sensitive: false
    enabled: true
